spring:
  application:
    name: cohegraph
  graphql:
    graphiql:
      enabled: true
    schema:
      introspection:
        enabled: true
    cors:
      allowed-origins: "*"
server:
  port: 9000
